esphome:
  name: testesp32
  friendly_name: TestESP32

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

external_components:
  - source: github://trenchcoatjedi/esphome-gps-pps-ntp-server@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP32 GPS Fallback Hotspot"
    password: "PASSWORD"

uart:
  id: gps_uart
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600

gps:
  id: gps_module
  uart_id: gps_uart
  latitude:
    name: "GPS Latitude"
  longitude:
    name: "GPS Longitude"
  altitude:
    name: "GPS Altitude"
  speed:
    name: "GPS Speed"
  course:
    name: "GPS Course"
  hdop:
    name: "GPS HDOP"
  update_interval: 20s

time:
  - platform: gps_pps_time
    id: gps_pps
    gps_id: gps_module
    pps_pin: GPIO1
    update_interval: 60s
    satellites:
      id: total_satellites
      name: "Satellites"
      icon: "mdi:satellite-variant"
      accuracy_decimals: 0
      state_class: measurement
      force_update: false
      disabled_by_default: false
      internal: false
    clock_offset:
      id: ntp_clock_offset
      name: "Clock Offset"
      icon: "mdi:clock-check-outline"
      unit_of_measurement: "µs"
      accuracy_decimals: 0
      state_class: measurement
    pps_drift:
      id: pps_raw_drift
      name: "PPS Drift"
      icon: "mdi:clock-alert-outline"
      unit_of_measurement: "µs"
      accuracy_decimals: 0
      state_class: measurement
    gps_time:
      id: gps_current_time
      name: "GPS Time"
      icon: "mdi:clock-outline"
      entity_category: "diagnostic"
    gps_satellites:
      id: gps_sat_count
      name: "GPS Satellites"
      icon: "mdi:satellite-variant"
      accuracy_decimals: 0
      state_class: measurement
    glonass_satellites:
      id: glonass_sat_count
      name: "GLONASS Satellites"
      icon: "mdi:satellite-variant"
      accuracy_decimals: 0
      state_class: measurement
    galileo_satellites:
      id: galileo_sat_count
      name: "Galileo Satellites"
      icon: "mdi:satellite-variant"
      accuracy_decimals: 0
      state_class: measurement

ntp_server:
  time_id: gps_pps

web_server:
  port: 80
